# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-27 11:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='CV name')),
                ('about', models.TextField(blank=True, null=True, verbose_name='about me')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CVs',
                'verbose_name_plural': 'CV',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=300, verbose_name='university name')),
                ('department', models.CharField(max_length=300, verbose_name='department name')),
                ('specialization', models.CharField(max_length=300, verbose_name='profession/specialization')),
                ('degree', models.PositiveIntegerField(choices=[(0, 'unset'), (1, 'bachelor'), (2, 'Master'), (3, 'Ph.D'), (4, 'incomplete higher')], default=0, verbose_name='degree')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.CV')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=300, verbose_name='organization name')),
                ('position', models.CharField(blank=True, max_length=300, null=True, verbose_name='working position')),
                ('region', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('date_from', models.DateField(verbose_name='date started to work')),
                ('date_to', models.DateField(verbose_name='date finished to work')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.CV')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='language name')),
                ('level', models.PositiveIntegerField(choices=[(0, 'Unset'), (1, 'Elementary'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Native')], default=0, verbose_name='knowledges level')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.CV')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('level', models.PositiveIntegerField(blank=True, default=0, verbose_name='experience/knowledges level')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.CV')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together=set([('name', 'cv')]),
        ),
    ]
