# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-27 11:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('label', models.CharField(blank=True, default='unlabeled', max_length=200)),
                ('priority', models.PositiveIntegerField(blank=True, default=0)),
                ('status', models.PositiveIntegerField(blank=True, default=0)),
                ('estimate_time', models.DurationField(blank=True, null=True, verbose_name='planning time')),
                ('original_time', models.DurationField(blank=True, null=True, verbose_name='real spent time')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='until date')),
                ('date_started', models.DateTimeField(blank=True, null=True, verbose_name='staring date')),
                ('date_finished', models.DateTimeField(blank=True, null=True, verbose_name='end date')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_by', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
